name: portfolio_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  build_runner: ^2.5.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  portfolio_api:
    path: ../portfolio_api

dev_dependencies:
  freezed: ^2.4.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
